# Generated by Django 3.2.9 on 2021-12-06 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bam_usuario',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('marca_modelo', models.CharField(max_length=20)),
                ('Proveedor', models.CharField(max_length=20)),
                ('linea', models.CharField(max_length=10)),
                ('imei', models.CharField(max_length=15)),
                ('sn', models.CharField(max_length=20)),
                ('sim', models.CharField(max_length=20)),
                ('apellido_nombre', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=9)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
